import { FONT_META, exportFontFamily, previewFontFamily } from './fonts-meta';
import { TOKEN_KEYS, type ThemePreset, type ThemeTokens } from './types';

export type ExportFormat = 'v4' | 'v3';
export type PreviewMode = 'light' | 'dark';

const PREVIEW_ID = '#themes-preview';
const PORTAL_ATTR = '[data-theme-preview]';

function tokenLines(tokens: ThemeTokens, indent = '  '): string {
  return TOKEN_KEYS.map((key) => `${indent}--${key}: ${tokens[key]};`).join('\n');
}

function fontVarLines(preset: ThemePreset, forExport: boolean, indent = '  '): string {
  const family = forExport ? exportFontFamily : previewFontFamily;
  return [
    `${indent}--font-sans: ${family(preset.fonts.sans)};`,
    `${indent}--font-heading: ${family(preset.fonts.heading)};`,
    `${indent}--font-mono: ${family(preset.fonts.mono)};`,
  ].join('\n');
}

/**
 * Expand `extraCss` for the live preview. Each rule uses `&` as a scope
 * placeholder; descendant rules are additionally emitted for portaled content
 * (dialog/select/tooltip render into <body> and carry `data-theme-preview`).
 */
function expandExtraCssForPreview(extraCss: string): string {
  return extraCss
    .split('\n')
    .map((line) => {
      const trimmed = line.trim();
      if (!trimmed) return '';
      const match = trimmed.match(/^(.*?)\{(.*)\}$/);
      if (!match) return '';
      const selectors = match[1].split(',').map((s) => s.trim());
      const body = match[2].trim();
      const expanded: string[] = [];
      for (const sel of selectors) {
        if (sel === '&') {
          expanded.push(PREVIEW_ID);
        } else if (sel === '.dark &') {
          expanded.push(`.dark ${PREVIEW_ID}`);
        } else if (sel.startsWith('& ')) {
          const rest = sel.slice(2);
          expanded.push(
            `${PREVIEW_ID} ${rest}`,
            `${PORTAL_ATTR}${rest}`,
            `${PORTAL_ATTR} ${rest}`
          );
        } else {
          expanded.push(sel.replaceAll('&', PREVIEW_ID));
        }
      }
      return `${expanded.join(', ')} { ${body} }`;
    })
    .filter(Boolean)
    .join('\n');
}

/**
 * CSS injected on the /themes page. Tokens are scoped to the preview wrapper
 * (light + dark) and to portaled demo content via [data-theme-preview],
 * which always carries the currently visible mode.
 */
export function buildPreviewCss(preset: ThemePreset, mode: PreviewMode): string {
  const activeTokens = mode === 'dark' ? preset.dark : preset.light;
  const activeShadow =
    mode === 'dark' ? preset.shadows?.dark : preset.shadows?.light;

  const shared = (forPortal: boolean) =>
    [
      `  --radius: ${preset.radius};`,
      fontVarLines(preset, false),
      `  font-family: var(--font-sans);`,
      forPortal && activeShadow ? `  --shadow: ${activeShadow};` : null,
    ]
      .filter(Boolean)
      .join('\n');

  const parts = [
    `${PREVIEW_ID} {\n${tokenLines(preset.light)}\n${shared(false)}${
      preset.shadows?.light ? `\n  --shadow: ${preset.shadows.light};` : ''
    }\n}`,
    `.dark ${PREVIEW_ID} {\n${tokenLines(preset.dark)}${
      preset.shadows?.dark ? `\n  --shadow: ${preset.shadows.dark};` : ''
    }\n}`,
    `${PORTAL_ATTR} {\n${tokenLines(activeTokens)}\n${shared(true)}\n}`,
    `${PREVIEW_ID} :is(h1, h2, h3, h4), ${PORTAL_ATTR} :is(h1, h2, h3, h4) { font-family: var(--font-heading); letter-spacing: -0.01em; }`,
  ];

  if (preset.extraCss) {
    parts.push(expandExtraCssForPreview(preset.extraCss));
  }

  return parts.join('\n\n');
}

function toRawChannels(value: string): string {
  // hsl(240 5.9% 10%) -> 240 5.9% 10% (v3 config consumes hsl(var(--x)))
  const match = value.match(/^hsl\(\s*([^)]+?)\s*\)$/);
  if (!match) return value;
  const inner = match[1];
  // Alpha values (hsl(... / 0.5)) can't be expressed as raw channels
  if (inner.includes('/')) return value;
  return inner;
}

function exportTokenLines(tokens: ThemeTokens, format: ExportFormat): string {
  return TOKEN_KEYS.map((key) => {
    const value = tokens[key];
    const out = format === 'v3' ? toRawChannels(value) : value;
    const note =
      format === 'v3' && out === value && value.includes('/')
        ? ' /* alpha color: keep as-is and use it directly, not via hsl(var(--x)) */'
        : '';
    return `    --${key}: ${out};${note}`;
  }).join('\n');
}

/** Paste-ready CSS for the user's globals.css (copy / download). */
export function buildExportCss(preset: ThemePreset, format: ExportFormat): string {
  const fontIds = [
    preset.fonts.sans,
    preset.fonts.heading,
    preset.fonts.mono,
  ].filter((id, index, all) => all.indexOf(id) === index);
  const imports = fontIds
    .map((id) => FONT_META[id].googleImport)
    .filter((url): url is string => Boolean(url))
    .map((url) => `@import url('${url}');`)
    .join('\n');

  const header = `/* ${preset.name} theme — generated by shadcn-extras (${
    format === 'v4' ? 'Tailwind v4' : 'Tailwind v3 / classic shadcn'
  } format) */`;

  const rootBlock = [
    `  :root {`,
    exportTokenLines(preset.light, format),
    `    --radius: ${preset.radius};`,
    fontVarLines(preset, true, '    '),
    preset.shadows?.light ? `    --shadow: ${preset.shadows.light};` : null,
    `  }`,
  ]
    .filter(Boolean)
    .join('\n');

  const darkBlock = [
    `  .dark {`,
    exportTokenLines(preset.dark, format),
    preset.shadows?.dark ? `    --shadow: ${preset.shadows.dark};` : null,
    `  }`,
  ]
    .filter(Boolean)
    .join('\n');

  const base = `@layer base {\n${rootBlock}\n\n${darkBlock}\n}`;

  const bodyFont = `@layer base {\n  body {\n    font-family: var(--font-sans);\n  }\n  h1, h2, h3, h4 {\n    font-family: var(--font-heading);\n  }\n}`;

  const effects = preset.extraCss
    ? `/* Theme effects (components need shadcn's data-slot attributes) */\n${preset.extraCss.replaceAll(
        '&',
        'body'
      )}`
    : null;

  return [header, imports, base, bodyFont, effects]
    .filter(Boolean)
    .join('\n\n');
}
