import type { ThemePreset } from '../types';

export const mono: ThemePreset = {
  id: 'mono',
  name: 'Minimal Mono',
  description: 'Pure grayscale, monospace type, zero radius — brutally minimal.',
  radius: '0rem',
  fonts: { sans: 'jetbrains', heading: 'jetbrains', mono: 'jetbrains' },
  light: {
    background: 'hsl(0 0% 100%)',
    foreground: 'hsl(0 0% 5%)',
    card: 'hsl(0 0% 100%)',
    'card-foreground': 'hsl(0 0% 5%)',
    popover: 'hsl(0 0% 100%)',
    'popover-foreground': 'hsl(0 0% 5%)',
    primary: 'hsl(0 0% 5%)',
    'primary-foreground': 'hsl(0 0% 100%)',
    secondary: 'hsl(0 0% 94%)',
    'secondary-foreground': 'hsl(0 0% 5%)',
    muted: 'hsl(0 0% 95%)',
    'muted-foreground': 'hsl(0 0% 40%)',
    accent: 'hsl(0 0% 88%)',
    'accent-foreground': 'hsl(0 0% 5%)',
    destructive: 'hsl(0 0% 25%)',
    'destructive-foreground': 'hsl(0 0% 100%)',
    border: 'hsl(0 0% 10%)',
    input: 'hsl(0 0% 40%)',
    ring: 'hsl(0 0% 5%)',
    'chart-1': 'hsl(0 0% 10%)',
    'chart-2': 'hsl(0 0% 35%)',
    'chart-3': 'hsl(0 0% 55%)',
    'chart-4': 'hsl(0 0% 72%)',
    'chart-5': 'hsl(0 0% 86%)',
  },
  dark: {
    background: 'hsl(0 0% 4%)',
    foreground: 'hsl(0 0% 96%)',
    card: 'hsl(0 0% 4%)',
    'card-foreground': 'hsl(0 0% 96%)',
    popover: 'hsl(0 0% 6%)',
    'popover-foreground': 'hsl(0 0% 96%)',
    primary: 'hsl(0 0% 96%)',
    'primary-foreground': 'hsl(0 0% 4%)',
    secondary: 'hsl(0 0% 14%)',
    'secondary-foreground': 'hsl(0 0% 96%)',
    muted: 'hsl(0 0% 12%)',
    'muted-foreground': 'hsl(0 0% 62%)',
    accent: 'hsl(0 0% 20%)',
    'accent-foreground': 'hsl(0 0% 96%)',
    destructive: 'hsl(0 0% 80%)',
    'destructive-foreground': 'hsl(0 0% 4%)',
    border: 'hsl(0 0% 90%)',
    input: 'hsl(0 0% 55%)',
    ring: 'hsl(0 0% 96%)',
    'chart-1': 'hsl(0 0% 92%)',
    'chart-2': 'hsl(0 0% 70%)',
    'chart-3': 'hsl(0 0% 50%)',
    'chart-4': 'hsl(0 0% 32%)',
    'chart-5': 'hsl(0 0% 18%)',
  },
  shadows: { light: 'none', dark: 'none' },
  extraCss: `& [data-slot='card'] { box-shadow: none; }`,
  swatches: ['hsl(0 0% 5%)', 'hsl(0 0% 40%)', 'hsl(0 0% 100%)', 'hsl(0 0% 72%)'],
};
